### ISSUE TITLE
When using mqtt over websocket, how can I specify the http request path?

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [mireo/async-mqtt5#15]
I am running my mqtt websocket server behind a reverse proxy which only makes it available on  /test, but not on / (there my homepage runs html code, but no mqtt).

How can I specify the http request parameters with this mqtt library when using boost beast?

**Comment by ksimicevic** [comment]
Hi, have you tried specifying the path to your server using the `mqtt_client::brokers` function like this?
```
async_mqtt5::mqtt_client<...> client(...);
client.brokers("localhost/test", port);
```

**Comment by 0xFEEDC0DE64** [comment]
thanks! I think that worked
